### ISSUE TITLE
Port mappings in service

### ISSUE THREAD

**Issue by volkanunsal** [segmentio/stack#112]
Is it possible to expose multiple port mappings in the service module? I have a service that needs to support more than one mapping. I notice that this is possible through task, but it's not supported by service.

**Comment by achille-roussel** [comment]
Unfortunately this is a limitation of the ELB, while the task definition can declare multiple ports, the load balancer can only attach to one port of the service.

**Comment by achille-roussel** [comment]
I'm gonna close this issue, feel free to re-open if you have follow up questions or comments.
