### ISSUE TITLE
Error parsing JSON: invalid character '$' 

### ISSUE THREAD

**Issue by lrhazi** [segmentio/stack#15]
Is the bellow error, an error ?

```
» terraform -v                         
Terraform v0.6.16

```
```
provider "aws" {
  region = "us-west-1"
}

module "stack" {
  source      = "github.com/segmentio/stack"
  name        = "mystack"
  environment = "prod"
  key_name    = "ml623-2"
  availability_zones = "us-west-1a,us-west-1c"
}
```

```
+ module.stack.s3_logs.aws_s3_bucket.logs
    acl:              "" => "private"
    arn:              "" => "<computed>"
    bucket:           "" => "mystack-prod-logs"
    force_destroy:    "" => "false"
    hosted_zone_id:   "" => "<computed>"
    policy:           "" => "Error parsing JSON: invalid character '$' looking for beginning of value"
    region:           "" => "<computed>"
    tags.#:           "" => "2"
    tags.Environment: "" => "prod"
    tags.Name:        "" => "mystack-prod-logs"
    website_domain:   "" => "<computed>"
    website_endpoint: "" => "<computed>"
```

**Comment by calvinfo** [comment]
That's odd... I wonder if `region` is not getting passed in properly? 

Our segment-access-logs module will take in the region and use it to interpolate the s3 access policy: https://github.com/segmentio/stack/blob/master/s3-logs/main.tf#L15

It should be passed from stack by default: https://github.com/segmentio/stack/blob/master/main.tf#L210

I can help take another look at this shortly, but I am confused about what's going on. Have you tried it in a different region by any chance?

**Comment by achille-roussel** [comment]
Not sure it's related but I think you'll need to set the region in the instantiation of the `stack` module:
```hcl
module "stack" {
  source = "github.com/segmentio/stack"
  region = "us-west-1"
  ...
}
```

**Comment by lrhazi** [comment]
Sorry guys. made many more changes and now cannot reproduce the error!
