### ISSUE TITLE
DNS Entry for RDS Cluster

### ISSUE THREAD

**Issue by StehlikC** [segmentio/stack#16]
We get the ability to put a dns_name on a service cluster, should we be able to do the same for the rds cluster? 

Something similar to what's referenced in this image (db.stack.local): https://segment.com/blog/the-segment-aws-stack/images/main.png

Sorry if this one doesn't make sense, I've never used RDS.

**Comment by calvinfo** [comment]
Ah we definitely could. Is the use case there in case you want to switch from one datastore to another but not update the app configuration? It seems reasonable–internally though we typically just reference the endpoint.

What do you think @achille-roussel @yields?

**Comment by StehlikC** [comment]
That's pretty much what I was thinking. I saw the reference to the endpoint in the pingdummy sample, but a dns could make the config a bit more simple.

**Comment by achille-roussel** [comment]
@liquidy and I discussed this actually and we thought it would be a good idea but just didn't have a use case for it.

I'll submit a PR, seems pretty easy to get done.

**Comment by achille-roussel** [comment]
This was addressed in https://github.com/segmentio/stack/pull/17

I'll close this issue, feel free to re-open if it's not working as you'd expected.
