### ISSUE TITLE
[Question] What subnet would a worker service be launched within?

### ISSUE THREAD

**Issue by chatu** [segmentio/stack#23]
I'm not sure how the ECS scheduler decides what subnet to pick for launching a service but I'm guessing it dependes on the subnets that have been configured for the ELB of the service. However, in the case of a worker, which does not have an ELB configured, how can it be guaranteed that it would be launched within an internal subnet as opposed to an external one?

**Comment by achille-roussel** [comment]
The worker will be launched in the subnets that have been passed to the `ecs-cluster` module, which by default are set to the internal subnets by the `stack` module.

see in `stack/main.tf`:
```hcl
module "ecs_cluster" {
    ...
    subnet_ids = "${module.vpc.internal_subnets}"
    ...
}
```

The external subnets are only used for the ELB that need to be exposed to the public, most likely when you use the `web-service` module.

**Comment by chatu** [comment]
Got it, thanks @achille-roussel for the clarification.

**Comment by achille-roussel** [comment]
You're welcome, I'll close the issue, feel free to re-open if needed.
