### ISSUE TITLE
Bootstrapping aws

### ISSUE THREAD

**Issue by roman-gliffy** [segmentio/stack#30]
Hi,

Could you elaborate on the process of bootstrapping aws from scratch?

And it would be interesting to hear about operation part: how the stack evolving? Do you use atlas or home grown tools to keep track of states and apply changes?

**Comment by achille-roussel** [comment]
Can you be more specific on what you mean by bootstrapping? There are links to the AWS documentation in the Readme, their documentation is pretty good to help with the initial steps (create an account + configure your development environment).
Once that's done you should be able to follow the instructions in the Readme to get started with terraform.

For now we use a remote terraform state on S3 to synchronize the changes between team members, and we simply run the plan/apply from our dev boxes, we're not using Atlas.
As our team grows our current approach will probably show its limits at some point but for now it works well enough.

**Comment by roman-gliffy** [comment]
There are few things that should be setup on the global level when an account is created. Like cloudtrail, a bucket to store tf states, policy to allow access to that bucket, some user accounts, and other such things. This is to allow terraform function effectively and keep its state safe remotely.

Oh, also wanted to ask if you run perform any testing to validate infrastructure from time to time, after terraform apply is completed or in between runs.
