### ISSUE TITLE
Opinionated fork

### ISSUE THREAD

**Issue by likwid** [segmentio/stack#31]
Hello,

First, cheers on such a great project! I have learned a ton just from reading the terraform structure y'all have created.

I have created a customized fork for my own needs. I want to make sure I do everything on the up and up licensing wise. I believe the main requirement is to keep your original Licence.md at the root of my repository, and maintain any copyright notices that you have (I'm not sure what these would be, I haven't come across any yet).

Additionally, I have given attribution at the top of my README, as I am very appreciative of the work y'all have done with this project.

Am I missing anything else? 

Thanks!

**Comment by calvinfo** [comment]
Note IANAL, but I think that should cover it! That's awesome too, we'd love to check it out if you have a link.

**Comment by achille-roussel** [comment]
I think this is it https://github.com/likwid/layercake

**Comment by likwid** [comment]
I might back my modifications out and just use stack, but customize my
module imports, but I wanted to get a handle on the structure.

I plan to use consul and nomad instead of ECS, as I have set that up
previously.

Yep Achille, that is the correct link! Thanks again for all y'alls hard
work on this, it's really great.
