### ISSUE TITLE
[Question] ECS cluster with public access

### ISSUE THREAD

**Issue by mthenw** [segmentio/stack#32]
Hey,

I saw https://github.com/segmentio/stack/pull/19 but I'm still not sure how can I make those hosts publicly accessible without bastion host. Security group from here provide access only for other SGs https://github.com/segmentio/stack/blob/master/ecs-cluster/main.tf#L117-L127

**Comment by gregwebs** [comment]
More info would be helpful here: why do you need public access beyone what an ELB provides? Are you having a problem sshing from the bastion?
