### ISSUE TITLE
S3 Bucket name already in use

### ISSUE THREAD

**Issue by stdevops** [segmentio/stack#33]
Testing the stack I received the error that the S3 Bucket name was already in use. I went through most of the code and couldn't find where to change it. Any help would be greatly appreciated.

**Comment by kanderson450** [comment]
The article & documentation definitely need some clarification.  I ran into this as well.

If you're following the Walkthrough, you define the following module:

```
module "stack" {
  source      = "github.com/segmentio/stack" # the module source
  name        = "pingdummy" # the name for our project
  environment = "prod" # the environment we're running in
  key_name    = "<my-ssh-key>" # reference a key you've previously created
}
```
However the **name** property is combined with the environment name to create an S3 bucket which must be globally unique.

That happens [here](https://github.com/segmentio/stack/blob/e51e3438ae74c8deca13168042e672454ee40ca8/s3-logs/main.tf#L20):
```
resource "aws_s3_bucket" "logs" {
  bucket = "${var.name}-${var.environment}-logs"
  //more stuff
}
```
So what you need to do is modify the name property in your "stack" module to be globally unique:
```
module "stack" {
  source      = "github.com/segmentio/stack" # the module source
  name        = "unique-name-pingdummy" # the name for our project
  environment = "prod" # the environment we're running in
  key_name    = "<my-ssh-key>" # reference a key you've previously created
}
```
@stdevops That should do the trick.
