### ISSUE TITLE
Bastion question

### ISSUE THREAD

**Issue by podviaznikov** [segmentio/stack#41]
Hello,

I was able to setup stack with bastion instance and 2 private instances.
I was able to ssh into bastion `ssh -i "my-pem.pem" ubuntu@bastion-ip`.
However I'm having trouble ssh-ing into the private ec2 instances.
I did `ssh -i "my-pem.pem" ubuntu@bastion-ip ssh private-ip` however I'm getting `Permission denied (publickey)` error.
Also I'm not really sure how bastion really works. Where does it take "my-pem.pem" file to ssh into private instances?

**Comment by josephsiefers** [comment]
@podviaznikov What was your solution for this?

**Comment by podviaznikov** [comment]
@josephsiefers ah, don't remember anymore. Should have posted it here
