### ISSUE TITLE
Null zone_id error, missing requirement?

### ISSUE THREAD

**Issue by adambarthelson** [segmentio/stack#43]
While following along with the pingdummy example and some of your documentation, I've been running into an issue where `terraform plan` and `terraform apply` both fail due to the error:

```* variable "main" is nil, but no error was reported```

I was able to determine the ambiguous error is caused by `${module.stack.zone_id}` missing while defining a service.  An example portion of my `terraform.tf`:

```
module "stack" {
  source      = "github.com/segmentio/stack"
  name        = "my_clients_name"
  environment = "prod"
  key_name    = "bastion-ssh"
  region      = "us-east-1"
  availability_zones = "us-east-1c,us-east-1d,us-east-1b,us-east-1e"
}

module "my_rails_service" {
  source         = "github.com/segmentio/stack/service"
  image          = "${aws_ecr_repository.my_rails_service.repository_url}"
  port           = 3000
  environment     = "${module.stack.environment}"
  cluster         = "${module.stack.cluster}"
  iam_role        = "${module.stack.iam_role}"
  zone_id         = "${module.stack.zone_id}" <----- cause of the error 
  security_groups = "${module.stack.internal_elb}"
  subnet_ids      = "${module.stack.internal_subnets}"
  log_bucket      = "${module.stack.log_bucket_id}"
  command = "bundle exec rails s -p 3000 -b '0.0.0.0'"
}
```

When digging down deep enough, I find that the missing field is an output of the [Terraform AWS ELB Resource](https://www.terraform.io/docs/providers/aws/r/elb.html#zone_id).  From the examples it seems like the default setup should be able to compute the zone_id, am I missing something?  (I fiddled around with the DNS module example in pingdummy for awhile as well, but no luck)

**Comment by gregwebs** [comment]
Its an output from the dns module. Weird that you are having an issue here.

**Comment by adambarthelson** [comment]
Could it be because I hadn't setup a Route53 domain with the AWS account?

**Comment by gregwebs** [comment]
yes, it would make sense to close this issue

**Comment by adambarthelson** [comment]
Ok, running into this issue still.

I started off with a fresh `terraform plan` and `terraform apply` to a barebones stack configuration for the defaults, I assumed I might need to execute things in a specific order due to dependencies.

```
provider "aws" {
  region = "us-east-1"
}

module "stack" {
  source      = "github.com/segmentio/stack"
  name        = "clientname"
  environment = "demo"
  key_name    = "bastion-ssh"
  region      = "us-east-1"
  availability_zones = "us-east-1d,us-east-1a,us-east-1b,us-east-1e"
}
```

All went well.

Next step I added some ECR repositories for the docker images my services will depend upon:

```
resource "aws_ecr_repository" "serviceone" {
  name = "serviceone"
}

resource "aws_ecr_repository_policy" "serviceonepolicy" {
  repository = "${aws_ecr_repository.serviceone.name}"
  policy = <<EOF
{
    "Version": "2008-10-17",
    "Statement": [
        {
            "Sid": "public permissions",
            "Effect": "Allow",
            "Principal": "*",
            "Action": [
                "ecr:PutImage",
                "ecr:InitiateLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:CompleteLayerUpload",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:BatchCheckLayerAvailability"
            ]
        }
    ]
}
EOF
}
```

Ran this, all was fine.  Decided to try and move on to adding a basic Stack Service for said image:

```
module "serviceone" {
  source         = "github.com/segmentio/stack/service"
  image          = "${aws_ecr_repository.serviceone.repository_url}"
  port             = 5000
  environment     = "${module.stack.environment}"
  cluster         = "${module.stack.cluster}"
  iam_role        = "${module.stack.iam_role}"
  zone_id         = "${module.stack.zone_id}"
  security_groups = "${module.stack.internal_elb}"
  subnet_ids      = "${module.stack.internal_subnets}"
  log_bucket      = "${module.stack.log_bucket_id}"
  dns_name       = "service_one"
}
```

It then fails, like I reported before:

```
Error running plan: 1 error(s) occurred:

* variable "main" is nil, but no error was reported
```

I intentionally chose a basic Stack Service as to avoid dealing with SSL / Domains like I had originally thought my problem was, but the problem still persists.  

What am I doing wrong?

**Comment by yields** [comment]
this is odd >.<, do you have a variable named `main`?

**Comment by adambarthelson** [comment]
negative, I believe it's on Segment's side.  Like I showed above, I believe it's related to the zone_id, and likely the DNS module.  I'm curious whether it has to do with the default configurations being focused on `us-west` at the moment.  The DNS module defaults may not be `us-east-1` friendly?  I'll look to test this theory once I get some time.

**Comment by adambarthelson** [comment]
I believe this may also be related to using Terraform v0.7.  I've rolled back to v0.6.16, and am checking out Stack release v0.1.  In the process of debugging now.

**Comment by adambarthelson** [comment]
Ran into several issues when rolling back, but did happen to come across this piece of information in a `terraform plan` on the old version:

```
+ module.stack.ecs_cluster.aws_ecs_cluster.main
    name: "" => "default"
```

May be related to my 0.7 troubles mentioned in this issue, will test theory by manually specifying Terraform configs specified in modules.

**Comment by adambarthelson** [comment]
Went full circle after applying several updates to the core modules themselves, and ended up back at the same "variable main is nil" error.  I'm stumped.  Moving on to something else.

**Comment by erikhh** [comment]
@adambarthelson I had this problem too, it turned out to be caused by the name of the service module. That value is reused as a ELB name which may only contain alphanumeric characters and hyphens. The stack code only replaces '/' by a hyphen. But if there's let's say a dot in the name of your service then this happens.

**Comment by yields** [comment]
@adambarthelson did you try planning/applying with env: `TF_LOG=debug`?

**Comment by yields** [comment]
@adambarthelson i think @erikhh is correct, stack will implicitly try to convert the service `image=` name into a ECS service name, you can try adding `name=` and it might solve the issue.

**Comment by adambarthelson** [comment]
I'll give this a try.

**Comment by adambarthelson** [comment]
That did resolve my problem! All of my kudos to you sir.
