### ISSUE TITLE
subnet_ids expect string but is list

### ISSUE THREAD

**Issue by esbenp** [segmentio/stack#59]
I get the following error when creating a web-service module.

```
Error configuring: 1 error(s) occurred:

* variable subnet_ids in module browser_client should be type string, got list
```

[Go the configuration from pingdummy](https://github.com/segmentio/pingdummy/blob/master/terraform.tf#L22). Unsure if this is a Stack issue or pingdummy but I thought I would report it regardless. Changed my config to join by `,` which seemed to fix the issue.

```
subnet_ids       = "${join(",",module.stack.external_subnets)}"
```

**Comment by achille-roussel** [comment]
This is the expected way of doing it I believe, there hasn't been work done on porting to terraform 0.7+ to support passing lists as variables.

**Comment by nmarcetic** [comment]
@achille-roussel We need to use terraform lower then v0.7 ? I saw this https://github.com/segmentio/stack/blob/master/circle.yml#L4 
I am getting a same problem as @esbenp , fixed with join
