### ISSUE TITLE
[question] is there a way to use docker-compose?

### ISSUE THREAD

**Issue by dazl** [segmentio/stack#62]
hi Is there a way to use docker-compose with stack or can a service only be set up with a single docker image? thank you

**Comment by achille-roussel** [comment]
Stack is designed to run on AWS using ECS, unfortunately ECS doesn't allow you to use docker-compose config files to describe the container you want to run (they have their own config format).

That being said, you can start multiple containers with the terraform config by declaring a new service, but each service will be in charge of a single docker image.

**Comment by mthenw** [comment]
@dazl you can try using [ecs-cli](https://github.com/aws/amazon-ecs-cli) for running services on cluster createad by stack. It supports docker-compose file .

**Comment by dazl** [comment]
thank you for the reply, makes sense. I was trying to see if there was a way of integrating  [ecs-cli compose](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) with terraform and stack.

**Comment by dazl** [comment]
thank you for your replies, yes I was trying to see if there was a way of integrating [ecs-cli](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) compose with terraform and stack. Will update if I work it out.

**Comment by nathanielks** [comment]
@dazl did you have any luck?

**Comment by dazl** [comment]
@nathanielks no luck, I'll close this
