### ISSUE TITLE
ECS-Cluster Cloud-Init Sequence Yields Yaml Parsing Errors for Private Docker Registry Auth

### ISSUE THREAD

**Issue by kanderson450** [segmentio/stack#79]
The last ecs-cluster cloud-init sequence deals with private docker registry authentication:
`- echo 'ECS_ENGINE_AUTH_DATA=${docker_auth_data}' >> /etc/ecs/ecs.config`

The problem is that the auth is in the form of JSON which causes Yaml parsing issues due to the colons present.

**Comment by achille-roussel** [comment]
Do you have an example of the error, as well as a value for `docker_auth_data` that triggers it?

**Comment by kanderson450** [comment]
@achille-roussel You'll find entries like this in your `/var/log/cloud-init-output.log`:
`util.py[WARNING]: Failed loading yaml blob`

The EC2 instance won't execute any of the sequences if it encounters any yaml issues.

I've just submitted PR #80 which resolves this issue.

**Comment by kanderson450** [comment]
@achille-roussel And an example value is:
`{"private.docker.registry.com": {"auth": "test-token","email": "test@example.com"}}`
The problem is the colons coming from the JSON format.

**Comment by chaserelock** [comment]
If anyone runs into this in the future, I needed to add a chomp due to a newline being inserted somewhere in the process of loading data into docker_auth_data
`"${chomp(var.docker_auth_data)}"`
