### ISSUE TITLE
Private subnet mistake on networking architecture diagram

### ISSUE THREAD

**Issue by rosswilson** [segmentio/stack#97]
In the README there's a diagram of the network subnet architecture:

![](https://github.com/segmentio/stack/raw/master/images/networking.png)

However, there's a mistake with the private subnet addresses in `us-west-2b` and `us-west-2c`. They should read `10.30.64.0/19` and `10.30.128.0/19` respectively. I can't find the original file to correct, only the png is in the repo.

If someone can point me to the original editable file I can submit a PR.

**Comment by achille-roussel** [comment]
:/ you're right.

@calvinfo do we still have the document that we generated this image from?

**Comment by calvinfo** [comment]
Ah yeah, it's a lucidchart, just updated it here: https://www.lucidchart.com/documents/edit/66fdbdd1-7414-4f55-8f7a-dd26b11f2792/0

![stack - network](https://cloud.githubusercontent.com/assets/487539/23380595/4ce01326-fcf0-11e6-9b19-7b36c88748fd.png)

Thanks @rosswilson!

**Comment by rosswilson** [comment]
No problem, glad I could help.
