### ISSUE TITLE
Attach ECS ASG to Web-Service ELB

### ISSUE THREAD

**Issue by micahlmartin** [segmentio/stack#98]
I'm not sure it's very clear how to achieve this. I have a web-service defined which spins up an ELB. The problem is that it comes up without any instances attached to it. I have to manually go to the ELB and add the ECS instances to it. I wanted to use the `aws_autoscaling_attachment_resource` but the right output variables arent' defined for me to leverage it. Ideally I would think it would be something like this:

```
# Create a new load balancer attachment
resource "aws_autoscaling_attachment" "asg_attachment" {
  autoscaling_group_name = "${module.stack.asg}"
  elb                    = "${module.myapp.elb}"
}
```

Am I doing this wrong or is this functionality missing?

Thanks!

**Comment by achille-roussel** [comment]
The ELBs are configured to have ECS tasks attach to them, them shouldn't attach to the EC2 instances directly.
Would you mind explaining why you want the ELB to attach to the Auto Scaling Group?
